### ISSUE TITLE
"'BOOLEANS' is not defined" in ldap_search module 

### ISSUE THREAD

**Issue by theodotos** [unchained-capital/ansible-ldap-modules#3]
Hello,

I have this task:

```
  - name: Get domains from LDAP
    ldap_search:
      base: "{{ base_dn }}"
      scope: subordinate
      filter: "(objectClass=domain)"
    register: ldap_domain_search
    delegate_to: "{{ ldap_server }}"
```

and I get this error when is run:

```
TASK [Get domains from LDAP] *******************************************************************************************************************************************
fatal: [mail.example.com -> ldap.example.com]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ldap.example.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_vQ_GsY/ansible_module_ldap_search.py\", line 231, in <module>\r\n    main()\r\n  File \"/tmp/ansible_vQ_GsY/ansible_module_ldap_search.py\", line 95, in main\r\n    'schema': dict(default=False, choices=(list(BOOLEANS)+['True', True, 'False', False])),\r\nNameError: global name 'BOOLEANS' is not defined\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

When I use the indentation scheme as per documentation I get syntax errors. For example the task is:

```
  - name: Get domains from LDAP
    ldap_search:
      base: "{{ base_dn }}"
        scope: subordinate
        filter: "(objectClass=domain)"
    register: ldap_domain_search
    delegate_to: "{{ ldap_server }}"
```

and I get this:

```
ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to have been in '/root/arena/playbooks/deploy_mailserver/deploy_mailserver_test.yml': line 60, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      base: "{{ base_dn }}"
        scope: subordinate
        ^ here
```

Is the documentation correct? Am I missing something obvious?
